### ISSUE TITLE
Transfer project to painless-software?

### ISSUE THREAD

**Issue by bittner** [vshn/django-probes#16]
I would volunteer to take over maintenance of this project.

- As VSHN your focus isn't really on the application side of supporting developers, let alone specialized on Django. It would remove a burden for you.
- If I have full control (instead of having to go through PRs via my own fork) it would be less of a burden to keep the project up-to-date.
- I'd prefer to transfer ownership on GitHub rather than creating a fork (and archiving this project here), so that we can retain the history of issues and PRs.
- I would suggest to leave your status of owners/maintainers on PyPI untouched, so you'd still have control over updating the package, just in case.

If that's sounds good enough to proceed, please initiate the transfer to the @painless-software organization.

Thank you for your understanding!

**Comment by tobru** [comment]
This makes sense, yes. I tried to initiate the process but it says "You don’t have the permission to create public repositories on painless-software" when clicking on "Transfer ownership". I've given you admin access to this repo so that you can do the transfer.

**Comment by tobru** [comment]
Transfer seems to have worked :+1:

**Comment by bittner** [comment]
Thanks @tobru! :medal_sports:
