### ISSUE TITLE
Django 4.1 support / requires_system_checks is a list now

### ISSUE THREAD

**Issue by simplylizz** [vshn/django-probes#24]
It throws this error on Django 4.1:
```
TypeError: requires_system_checks must be a list or tuple.
```

https://docs.djangoproject.com/en/4.0/howto/custom-management-commands/#django.core.management.BaseCommand.requires_system_checks

**Comment by bittner** [comment]
Thanks for reporting!

Can you provide more details on how to reproduce the error? Also, a stack trace would help.

**Comment by simplylizz** [comment]
Just run your management command you'll stumble upon this here:
https://github.com/painless-software/django-probes/blob/c24b152eed823a3bd4fc785f1ca1e237cc6cf8e3/django_probes/management/commands/wait_for_database.py#L67

**Comment by bittner** [comment]
Do you think you can provide a PR to fix this problem?

Add a test first to demonstrate the issue.

**Comment by simplylizz** [comment]
Sorry, I meant Django 4.1, perhaps it was working in 4.0.

Also, for myself I've solved this just by monkey patching:
```python
from django_probes.<...> import Command
Command.requires_system_checks = []
```

> Do you think you can provide a PR to fix this problem?

Not sure that I'll have time by myself to make a proper fix (with tests and backward compatibility), but let me check, maybe I could delegate this :)

**Comment by bittner** [comment]
I updated the test infrastructure. When you run `tox` locally, it now also covers Django 4.1.

And, yeah, the [current tests](https://github.com/painless-software/django-probes/blob/main/tests/unit/test_cli.py) don't fail, because they both call `wait_for_database` directly instead of via the management command infrastructure (aka `argparse`).
